  FUNCTION F_MODELO_MENSAGEM(P_VARIAVEL_EMAIL IN VARCHAR2) RETURN L_MENSAGEM_DEC PIPELINED AS

       /*FUNCAO RESPONSAVEL DE CRIAR O MODELO DE EMAIL*/

    CORPO_MSG         VARCHAR2(4000);
    CLASSIFICACAO_MSG NUMBER;
    TPO_ID_MSG        NUMBER;
    GRP_ID_MSG        NUMBER;
    MOD_ID_MSG        NUMBER;
    ASSUNTO_MSG       VARCHAR2(100);
    NOME_EVENTO_EMAIL VARCHAR2(50) := 'CADIN_COMUNICADO';
    CONT              NUMBER(2) := 0;
    VARIAVEL_ARRAY    DBMS_SQL.VARCHAR2_TABLE;
    RETORNO           T_MENSAGEM_DEC;

    CURSOR C_ATRIBUTOS IS
      SELECT * FROM (WITH TEST AS (SELECT TO_CHAR(P_VARIAVEL_EMAIL) COL FROM DUAL)
               SELECT REGEXP_SUBSTR(COL, '[^;]+', 1, LEVEL) NOME FROM TEST
               CONNECT BY LEVEL <= LENGTH(REGEXP_REPLACE(COL, '[^;]+')) + 1);


    REG_ATRIBUTO C_ATRIBUTOS%ROWTYPE;

  BEGIN

    ----CRIAR VARIAVEL DE REFERENCA
    VARIAVEL_ARRAY(0) := '@razaosocialcontribuinte';


    BEGIN

      -- CONSULTAR MODELO DE MENSAGEM
      SELECT DBMS_LOB.SUBSTR(MS.MOD_CORPO),
             MS.MOD_ASSUNTO,
             MS.MOD_CLASSIFICACAO,
             MS.TPO_ID,
             MS.GRP_ID,
             MS.MOD_ID

        INTO CORPO_MSG,
             ASSUNTO_MSG,
             CLASSIFICACAO_MSG,
             TPO_ID_MSG,
             GRP_ID_MSG,
             MOD_ID_MSG
        FROM TAXPAOC.TAB_DEC_MODELO_MENSAGEM MS, TAXPAOC.TAB_DEC_EVENTO DE
       WHERE DE.EVE_ID = NOME_EVENTO_EMAIL
         AND DE.MOD_ID = MS.MOD_ID;

      -- ADICIONAR ATRIBUTOS DAS VARIAVEIS REFERENCIADAS
      OPEN C_ATRIBUTOS;
      LOOP
        FETCH C_ATRIBUTOS
          INTO REG_ATRIBUTO;
        EXIT WHEN C_ATRIBUTOS%NOTFOUND;

        CORPO_MSG := REPLACE(CORPO_MSG, VARIAVEL_ARRAY(CONT), REG_ATRIBUTO.NOME);
        CONT      := CONT + 1;

      END LOOP;
      CLOSE C_ATRIBUTOS;

      RETORNO.CORPO_MSG         := CORPO_MSG;
      RETORNO.ASSUNTO_MSG       := ASSUNTO_MSG;
      RETORNO.CLASSIFICACAO_MSG := CLASSIFICACAO_MSG;
      RETORNO.TPO_ID_MSG        := TPO_ID_MSG;
      RETORNO.GRP_ID_MSG        := GRP_ID_MSG;
      RETORNO.MOD_ID_MSG        := MOD_ID_MSG;

      PIPE ROW(RETORNO);

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('MODELO DE MENSAGEM NAO ENCONTRADO - F_MODELO_MENSAGEM');
    END;

  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20102,'ERRO AO CONSULTA MODELO DE MENSAGEM - FUNCTION (F_MODELO_MENSAGEM)' ||SQLERRM);

  END F_MODELO_MENSAGEM;